### ISSUE TITLE
[netlify-cms] Add ncw-reorder

### ISSUE THREAD

**Issue by okdistribute** [d4rekanguok/netlify-cms-widgets#34]
Hi, great project, looking forward to using it! Also, your i18n widget will be super helpful, too!

Is the unpkg script ready for use with `ncw-reorder`? Currently getting "No control for widget 'ncw-reorder'." when trying to use it. Should I use the import script and manually register the widget instead?

Thanks so much!

<script src="https://unpkg.com/@ncwidgets/netlify-cms@^0.7.0/dist/netlify-cms.js"></script>

```yml
 - name: settings
   label: Settings
   delete: false
   folder: _data/settings
   create: true
   fields: 
     - label: Section Order
       name: order
       widget: ncw-reorder
       collection: sections 
       editor:
          preview: true
       create: false
       id_field: id
       display_template: '{{id}} | {{title}}'
       fields:
         - { label: "Id", name: "id", widget: "string" }

 - name: sections
    label: Map Sections
    folder: _data/sections
    editor: 
      preview: false
    create: true
    slug: "{{slug}}"
    extension: 'json'
    fields: 
      - label: Identifer
        name: id 
        widget: string
      - label: Title
        name: title

...etc
```

![Screenshot from 2020-04-13 22-55-46](https://user-images.githubusercontent.com/633012/79190891-398b6280-7dda-11ea-8574-86d11a491d89.png)
