### ISSUE TITLE
unselect an item from a parent optional field 

### ISSUE THREAD

**Issue by magomimmo** [d4rekanguok/netlify-cms-widgets#37]
Say you define a `ncw-file-relation` which is optional. If I'm not wrong, after you select an item, you can only change the selected item with another and there is no way to unselect it to leave the field blank.

**Comment by d4rekanguok** [comment]
I think you have discovered a bug, since it should work that way (Ive just [tried here](https://custom-widgets.netlify.app/#/collections/posts/entries/hej)). Would be really helpful if we can reproduce this bug!

**Comment by magomimmo** [comment]
Thanks Derek, but your sample applies to multiple selections. Here is a minimum case to reproduce the bug:

```yaml
collections:
  - label: 'Lookup tables'
    name: 'lookups'
    files:
      # Tools
      - label: 'Tools'
        name: 'tools'
        file: 'data/tools.json'
        fields:
          - label: 'Tools'
            label_singular: 'Tool'
            name: 'types'
            widget: 'list'
            fields:
              - label: 'Tool'
                name: 'name'
                widget: 'string'
              - label: 'id'
                name: 'id'
                widget: 'ncw-id'
  # Minimal sample
  - label: 'Minimal'
    name: 'minimal'
    folder: 'content/minimal'
    create: true
    slug: '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}'
    editor:
      preview: false
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Tool'
        name: 'tool'
        widget: 'ncw-file-relation'
        collection: 'lookups'
        file: 'tools'
        target_field: 'types'
        id_field: 'id'
        display_fields: 'name'
        required: false
```

And here is a minmal content for the `tools.json` file:

```json
{
  "types": [
    {
      "id": "sTX0yM2qt",
      "name": "Pennello"
    },
    {
      "id": "YXVUmNmp7",
      "name": "Pennello, Tampone"
    },
    {
      "id": "fszVCXn9O",
      "name": "Siringa"
    },
    {
      "id": "YvBAGjXsG",
      "name": "Tampone"
    },
    {
      "id": "MoNBxcZSG",
      "name": "Tampone, straccio"
    }
  ]
}
```
It the file collection referenced in the minimal folder collection is not required, you can't set it void after you have previously chosen an item.

But there is even another issue: you can't reference a field different form the `id` in the slug of the minimal folder collection referencing the file collection.
