### ISSUE TITLE
Display_fields accept one field only

### ISSUE THREAD

**Issue by magomimmo** [d4rekanguok/netlify-cms-widgets#39]
It seems to me that even if the option `display_fields` has plural form, it works with one field only. Moreover, it would be great, when you have more fields in a file collections, to be able via `display_fileds` to display to the user more than one field value. 

Am I wrong?

Thanks so much for your life-saver file-relation :+1:

**Comment by d4rekanguok** [comment]
You are right, this is something I overlooked. Will work to fix this soon!

Also thank you for the kind works — I can't wait to bring file-relation back to netlify-cms itself.

**Comment by magomimmo** [comment]
Now the `hide: true` option for collections works like a charme with your stuff. Thanks so much

**Comment by magomimmo** [comment]
>  I can't wait to bring file-relation back to netlify-cms itself.

Dereck, IMHO, with some more work your `ncw-file-relation` widget will be ready for primetime :-)

**Comment by d4rekanguok** [comment]
I've added support for multiple `display_fields` + `display_summary` in #41. You can now use a string template via `display_summary`:

```json
// data
{
  "categories": [{
    "name": "Cat",
    "desc": "Cats are cool",
    "id": "cats-GQnCNUpF2"
  }]
}
```

```yaml
      - label: Category (Single)
        name: single
        widget: ncw-file-relation
        collection: setting
        file: cats
        target_field: cats
        id_field: id
        display_fields: ["name", "desc"]           # label: "Cat Cats are cool"
        display_summary: "{{name}}: {{desc}}"      # label: "Cat: Cats are cool"
        hint: Same as above, but only with single choice
```

Please let me know if you find any issues!

**Comment by magomimmo** [comment]
Or you did not update the release on the CDN (now is 0.7.4), or I did not understand how it works, or there is something wrong. I define del following files collection:

```yaml
  - label: Editable Lookups
    name: editables
    files:
      # Animals file collection for testing display_fields
      - label: Animals
        name: animals
        file: data/animals.json
        fields:
          - label: Animals
            label_singular: Animal
            name: animals
            widget: list
            fields:
              - label: Name
                name: name           # <- name
                widget: string
              - label: Description  # <- description
                name: description
                widget: string
              - label: ID
                name: id               # <- id
                widget: ncw-id
```

And here is the corresponding `animals.json` file after having added a couple of elments to it

```json
{
  "animals": [
    {
      "id": "CrQz63Yu3",
      "name": "Cat",
      "description": "Cats are cool"
    },
    {
      "id": "-PhfciJqa",
      "name": "Dog",
      "description": "Dogs are sweety"
    }
  ]
}
```

How you configure the following folder collection referencing the above file collection to be able to:

1. show the display_summary (e.g. `"{{name}}: {{description}}"`) from the file collection in the summary of the folder collection (e.g. `"{{title}}: {{animal}}")`? 
1. show the `display_fields` from the file collection in the `animal` field of the folder collection?

```yaml
  # Display folder collection for testing display_fields and
  # display_summary
  - label: Display
    name: display
    slug: '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{title}}'
    summary: '{{title}} ({{animal}})'
    folder: content/display
    create: true
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Animal
        name: animal
        widget: ncw-file-relation
        collection: editables
        file: animals
        target_field: animals
        id_field: id
        display_fields: ["name", "description"]
        display_summary: "{{name}}: {{description}}"
```

Where am I wrong?

Thanks so much

**Comment by d4rekanguok** [comment]
Hi @magomimmo! We're actually on 0.8.1 now, could you try again on the latest version?

**Comment by magomimmo** [comment]
I just discovered it....I'll try in the afternoon (italian time)

**Comment by magomimmo** [comment]
yep. the display summary works in the folder collection field referencing the file, but I would like to show it in the summary of the folder collection summary as well.

**Comment by d4rekanguok** [comment]
> I mean how could I set the folder collection summary in such away that it references a field in the entry of the file collection (e.g. name or description or both)?

Ohh I think I get it now. Hhhm I think if we store the data of the selected fields, it might work, e.g.

```yml
summary: "{{animal.name}}"
```

Or we may store the summary field itself, so you can do
```yml
summary: "{{animal.summary}}"
```

Is this what you meant?

**Comment by magomimmo** [comment]
Yes, it's what I mean. To me both solutions are ok. Perhaps the summary based solution is less flexible, but more intuitive. 

BTW: The same problem applies to `relation` widget when using `ncw-id` widget as universal unique id of the entries.

Here is a code snippet:

```yaml
  - label: Referenced Folder collection
    name: referenced
    identifier_field: id
    folder: content/referenced
    create: true
    slug: '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{last}}-{{first}}'
    summary: '{{last}}, {{first}}'
    editor:
      preview: false
    fields:

      - label: ID
        name: id
        widget: ncw-id

      - label: Last Name
        name: last
        widget: string
        
      - label: First Name
        name: first
        widget: string

  - label: Referencing Folder Collection
    name: referencing
    identifier_field: id
    folder: content/referencing
    create: true
    slug: '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{referenced.last}}'
    summary: '{{referenced.last}}, {{referenced.first}}-{{referenced}}'
    editor:
      preview: false
    fields:

      - label: ID
        name: id
        widget: ncw-id

      - label: Referenced Entry
        name: referenced
        widget: relation
        collection: referenced
        searchFields: ['last', 'first']
        displayFields: ['{{last}}, {{first}}']
        valueField: id
```
As you can see in the attachment, only the referenced `ncw-id is accessible if the referenced entry. The problems seems to be almost the same as for your file relation widget. 
___
![sample](https://user-images.githubusercontent.com/1448905/81550444-884bfe00-9380-11ea-8ac1-31b1892e5319.png)
